services:
  yacy:
    image: yacy/yacy_search_server:latest
    container_name: yacy_search_server
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8443:8443"
    volumes:
      - ./yacy_search_server_data:/opt/yacy_search_server/DATA
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "2"
