services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ct_heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    ports:
      - 1081:80
      - 1444:443
    restart: unless-stopped

