version: '3.7'
services:
  fileflows:
    image: revenz/fileflows
    restart: unless-stopped
    #runtime: nvidia
    ports:
      - "19200:5000"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      #- NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      #- NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./temp:/temp
      - ./data:/app/Data
      - ./logs:/app/Logs
      - ./dir:/app/common
